version: "3"

networks:
  stack_dev:
    external: true

services:
  scs_back:
    image: golang:1.24.4
    container_name: "scs_back"
    networks:
      - stack_dev
    ports:
      - "5082:8000"
    volumes:
      - ${DEVPATHCLIENTES}/scs/back:/app
      - ${DEVPATHCLIENTES}/scs/server/cespare:/go/pkg/mod/github.com/cespare
      - ${DEVPATHCLIENTES}/scs/server/reflex:/go/bin/reflex
    command: "/bin/sh -c 'cd /app && reflex -c /app/reflex.conf'"

  scs_front:
    container_name: "scs_front"
    image: "node:lts"
    working_dir: /app
    networks:
      - stack_dev
    volumes:
      - ${DEVPATHCLIENTES}/scs/front:/app
    command: "npm run dev"
    ports:
      - "8082:3000"
