/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Angle: typeof import('./src/components/calculadora/src/components/converters/Angle.vue')['default']
    App: typeof import('./src/components/calculadora/src/App.vue')['default']
    Area: typeof import('./src/components/calculadora/src/components/converters/Area.vue')['default']
    BtnToTop: typeof import('./src/components/totop/BtnToTop.vue')['default']
    Calculadora: typeof import('./src/components/calculadora/Calculadora.vue')['default']
    Calculator: typeof import('./src/components/calculadora/src/Calculator.vue')['default']
    Calendario: typeof import('./src/components/Calendario/Calendario.vue')['default']
    Data: typeof import('./src/components/calculadora/src/components/converters/Data.vue')['default']
    DateCalculation: typeof import('./src/components/calculadora/src/components/calculators/DateCalculation.vue')['default']
    Dialog: typeof import('./src/components/modals/Dialog.vue')['default']
    EfectCircles: typeof import('./src/components/efectCircles.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    Energy: typeof import('./src/components/calculadora/src/components/converters/Energy.vue')['default']
    Hour: typeof import('./src/components/calculadora/src/components/converters/Hour.vue')['default']
    Length: typeof import('./src/components/calculadora/src/components/converters/Length.vue')['default']
    Modal: typeof import('./src/components/modals/Modal.vue')['default']
    ModalConfirmacao: typeof import('./src/components/modals/ModalConfirmacao.vue')['default']
    Power: typeof import('./src/components/calculadora/src/components/converters/Power.vue')['default']
    Pressure: typeof import('./src/components/calculadora/src/components/converters/Pressure.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scientific: typeof import('./src/components/calculadora/src/components/calculators/Scientific.vue')['default']
    Screen: typeof import('./src/components/calculadora/src/components/converters/Screen.vue')['default']
    Standard: typeof import('./src/components/calculadora/src/components/calculators/Standard.vue')['default']
    Temperature: typeof import('./src/components/calculadora/src/components/converters/Temperature.vue')['default']
    Toast: typeof import('./src/components/toast/Toast.vue')['default']
    Volume: typeof import('./src/components/calculadora/src/components/converters/Volume.vue')['default']
    WeightAndMass: typeof import('./src/components/calculadora/src/components/converters/WeightAndMass.vue')['default']
  }
}
