import { reactive } from "vue";

export const store = reactive({
  operacoes: [
    {
      data: "2024-03-25",
      tick: "TSLA34",
      qtdCompra: 400,
      qtdVenda: null,
      valorCompra: 26.5,
      valorVenda: null,
    },
    {
      data: "2024-06-06",
      tick: "TSLA34",
      qtdCompra: 350,
      qtdVenda: null,
      valorCompra: 29.12,
      valorVenda: null,
    },
    {
      data: "2024-06-17",
      tick: "TSLA34",
      qtdCompra: 400,
      qtdVenda: null,
      valorCompra: 31.65,
      valorVenda: null,
    },
    {
      data: "2024-07-12",
      tick: "TSLA34",
      qtdCompra: null,
      qtdVenda: 400,
      valorCompra: null,
      valorVenda: 31.26,
    },
    {
      data: "2024-07-12",
      tick: "TSLA34",
      qtdCompra: null,
      qtdVenda: 750,
      valorCompra: null,
      valorVenda: 32.89,
    },
  ] as any,
  tipoOperacao: "compra",
  novaOperacao: {
    data: new Date().toISOString().split("T")[0],
    tick: "TSLA34",
    qtdCompra: null,
    qtdVenda: null,
    valorCompra: null,
    valorVenda: null,
  },
  corretoras: [
    {
      nome: "XP Investimentos",
      data: "2023-04-10",
      info: "Conta PJ",
      moeda: "BRL",
      cor: "green",
      ticks: ["BBAS3", "PETR4"],
    },
    {
      nome: "GENIAL INVESTIMENTOS",
      data: "2022-09-15",
      moeda: "BRL",
      cor: "blue",
      info: "Poupança",
      ticks: ["ITUB4"],
    },
    {
      nome: "NOMADE",
      data: "2021-02-01",
      moeda: "USD",
      cor: "yellow",
      info: "Conta Corrente",
      ticks: ["NU", "VALE3", "B3SA3"],
    },
  ] as any,
  tickers: [
    {
      id: 1,
      corretora: 1,
      name: "NVDC34",
      datacompra: "2024-01-15",
      datavenda: "",
    },
    {
      id: 2,
      corretora: 1,
      name: "TSLA34",
      datacompra: "2024-01-15",
      datavenda: "",
    },
    {
      id: 3,
      corretora: 2,
      name: "AMZO34",
      datacompra: "2024-01-15",
      datavenda: "",
    },
    {
      id: 4,
      corretora: 2,
      name: "NFLX34",
      datacompra: "2024-01-15",
      datavenda: "",
    },
  ],
});
