import { reactive } from "vue";

export const store = reactive({
  operacoes: [
    {
      data: "2024-03-25",
      tick: "TSLA34",
      qtdCompra: 400,
      qtdVenda: null,
      valorCompra: 26.5,
      valorVenda: null,
    },
    {
      data: "2024-06-06",
      tick: "TSLA34",
      qtdCompra: 350,
      qtdVenda: null,
      valorCompra: 29.12,
      valorVenda: null,
    },
    {
      data: "2024-06-17",
      tick: "TSLA34",
      qtdCompra: 400,
      qtdVenda: null,
      valorCompra: 31.65,
      valorVenda: null,
    },
    {
      data: "2024-07-12",
      tick: "TSLA34",
      qtdCompra: null,
      qtdVenda: 400,
      valorCompra: null,
      valorVenda: 31.26,
    },
    {
      data: "2024-07-12",
      tick: "TSLA34",
      qtdCompra: null,
      qtdVenda: 750,
      valorCompra: null,
      valorVenda: 32.89,
    },
  ] as any,
  tipoOperacao: "compra",
  novaOperacao: {
    data: new Date().toISOString().split("T")[0],
    tick: "TSLA34",
    qtdCompra: null,
    qtdVenda: null,
    valorCompra: null,
    valorVenda: null,
  },
  corretoras: [
    {
      nome: "XP Investimentos",
      data: "2023-04-10",
      info: "Conta PJ",
      moeda: "BRL",
      cor: "green",
      ticks: ["BBAS3", "PETR4"],
    },
    {
      nome: "GENIAL INVESTIMENTOS",
      data: "2022-09-15",
      moeda: "BRL",
      cor: "blue",
      info: "Poupança",
      ticks: ["ITUB4"],
    },
    {
      nome: "NOMADE",
      data: "2021-02-01",
      moeda: "USD",
      cor: "yellow",
      info: "Conta Corrente",
      ticks: ["NU", "VALE3", "B3SA3"],
    },
  ] as any,
  tickers: [
    {
      id: 1,
      corretora: 1,
      name: "NVDC34",
      datacompra: "2024-01-15",
      datavenda: "",
    },
    {
      id: 2,
      corretora: 1,
      name: "TSLA34",
      datacompra: "2024-01-15",
      datavenda: "",
    },
    {
      id: 3,
      corretora: 2,
      name: "AMZO34",
      datacompra: "2024-01-15",
      datavenda: "",
    },
    {
      id: 4,
      corretora: 2,
      name: "NFLX34",
      datacompra: "2024-01-15",
      datavenda: "",
    },
  ],
  ativos: {
    ASML: {
      nome: "ASML Holding NV",
      operacoes: [
        {
          cv: "C",
          data: "2025-07-29",
          c: 2.0,
          v: null,
          saldo: 2.0,
          valor: 725.68,
          compra: 1451.35,
          venda: null,
          carteira: 1451.35,
          pm: 725.68,
          margem: null,
          lp: null,
          div: null,
        },
      ],
      performance: {
        posicao: 1442.92,
        atual: 721.46,
        resultado: {
          percentual: "0.58%",
          valor: 8.43,
        },

        meta: 907.09,
        diferenca: 4.21,
        investido: 1451.35,
        pmc: 725.68,
        stocks: 2.0,
      },
    },
    PLTR: {
      nome: "Palantir Technologies Inc.",
      operacoes: [
        {
          cv: "C",
          data: "2025-02-18",
          c: 10.0,
          v: null,
          saldo: 10.0,
          valor: 121.0,
          compra: 1210.0,
          venda: null,
          carteira: 1210.0,
          pm: 121.0,
          margem: null,
          lp: null,
          div: null,
        },
        {
          cv: "C",
          data: "2025-02-20",
          c: 5.0,
          v: null,
          saldo: 15.0,
          valor: 104.88,
          compra: 524.38,
          venda: null,
          carteira: 1734.38,
          pm: 115.63,
          margem: null,
          lp: null,
          div: null,
        },
        {
          cv: "C",
          data: "2025-05-07",
          c: 5.0,
          v: null,
          saldo: 20.0,
          valor: 108.78,
          compra: 543.89,
          venda: null,
          carteira: 2278.27,
          pm: 113.91,
          margem: null,
          lp: null,
          div: null,
        },
        {
          cv: "C",
          data: "2025-06-25",
          c: 8.0,
          v: null,
          saldo: 28.0,
          valor: 146.26,
          compra: 1170.04,
          venda: null,
          carteira: 3448.31,
          pm: 123.15,
          margem: null,
          lp: null,
          div: null,
        },
        {
          cv: "C",
          data: "2025-07-01",
          c: 7.0,
          v: null,
          saldo: 35.0,
          valor: 129.89,
          compra: 909.22,
          venda: null,
          carteira: 4357.53,
          pm: 124.5,
          margem: null,
          lp: null,
          div: null,
        },
        {
          cv: "C",
          data: "2025-07-03",
          c: 5.0,
          v: null,
          saldo: 40.0,
          valor: 133.72,
          compra: 668.58,
          venda: null,
          carteira: 5026.11,
          pm: 125.65,
          margem: null,
          lp: null,
          div: null,
        },
      ],
      performance: {
        posicao: 6327.6,
        atual: 158.19,
        resultado: {
          percentual: "25,89%",
          valor: 1301.49,
        },
        meta: 157.07,

        diferenca: 32.54,
        investido: 5026.11,
        pmc: 125.65,
        stocks: 40.0,
        precoAtual: 158.19,
      },
    },
  },
});
